name: CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up protoc
      uses: arduino/setup-protoc@master
    - name: Install miniconda
      uses: goanpeca/setup-miniconda@master
      with:
        python-version: '3.7'
        auto-update-conda: true
    - name: Update PATH
      shell: bash -l {0}
      run: |
        echo "::add-path::$(dirname $(which conda))"
        echo "::add-path::$(dirname $(which python))"
    - name: Install dependencies
      run: |
        conda install --file requirements.txt
        conda install -c rdkit rdkit
        conda install pylint
    - name: Install ord_schema
      run: |
        cd "${GITHUB_WORKSPACE}"
        python setup.py build_py
        python setup.py install
    - name: Run tests
      run: |
        shopt -s globstar
        cd "${GITHUB_WORKSPACE}"
        for TEST_FILENAME in ord_schema/**/*_test.py; do \
          echo "Running tests in ${TEST_FILENAME}"; \
          python "${TEST_FILENAME}"; \
        done
    - name: Run pylint
      run: |
        cd "${GITHUB_WORKSPACE}"
        pylint ord_schema
    - name: Test notebooks
      run: |
        pip install treon
        treon
