name: Setup

on: push

jobs:
  update_proto_py:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: arduino/setup-protoc@master
    - name: Setup git
      run: |
        cd "${GITHUB_WORKSPACE}"
        git config user.name "run_protoc"
        git config user.email "run_protoc@master"
    - name: Run protoc
      run: |
        cd "${GITHUB_WORKSPACE}"
        for proto_filename in proto/*.proto; do
          protoc --proto_path=.. --python_out=. "ord-schema/${proto_filename}"
        done
    - name: Commit updates
      run: |
        cd "${GITHUB_WORKSPACE}"
        git add ord_schema/proto/*_pb2.py
        if git commit -m "Run protoc (GitHub action)"; then
          # GITHUB_REF looks like refs/heads/<BRANCH>; we only want BRANCH
          git push origin "${GITHUB_REF:11}"
        fi
